[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --no-input"]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn medify_backend.wsgi:application --bind 0.0.0.0:$PORT"
