[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["chmod +x build.sh && ./build.sh"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --no-input"]

[start]
cmd = "chmod +x start.sh && ./start.sh"
