[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --no-input"]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn medify_backend.wsgi:application --bind 0.0.0.0:$PORT"
